### ISSUE TITLE
Github Organization

### ISSUE THREAD

**Issue by bistcuite** [gliimly/gliimly#1]
Hi.
I've been exploring the programming language you've created, and I'm really impressed! I have a suggestion.
Instead of managing Gliimly under a personal account, I recommend creating a GitHub organization. An organization offers several advantages over a personal account, such as:

Adding new members: Collaborate with others more easily.
Using Kanban boards: Streamline project management.
Centralizing related repositories: Keep all your project resources in one place.

I'm eager to contribute to this language and would appreciate it if you could migrate the repository to a GitHub organization.

**Comment by gliimly** [comment]
Hi, please see [CONTRIBUTING.md](https://github.com/gliimly/gliimly/blob/main/CONTRIBUTING.md) for more details on this.
